### PR TITLE
Swift UI Update.

### PR DESCRIPTION
**Pull request by ShikiSuen**
The current AppKit-based r128x-GUI is plagued with compatibility issues against the SDKs of recent macOS releases.
I rewrote the entire r128x-GUI using SwiftUI, targeting macOS 12 and later.

Here comes a notarized app package: 
[r128x-swiftui-0.4.zip](https://github.com/audionuma/r128x/files/12139218/r128x-swiftui-0.4.zip)

### CODE REVIEW

**Comment by ShikiSuen** [comment]
Showcase.
https://github.com/audionuma/r128x/assets/3164826/38862a38-49d4-4e2c-84e3-955e9d385cdd

**Comment by audionuma** [comment]
Hello, as I mentioned on another issue, I have no more access to a MacOS computer. I don't feel comfortable to merge code that i cannot test.
I will therefore make a link to your fork on the read me page so that interested users can go there.
Thanks for your efforts.

**Comment by ShikiSuen** [comment]
@audionuma Thank you for your response. Are you able to continue developing on Windows machine?
I guess that the core backends can be possibly made cross-platform?

**Comment by audionuma** [comment]
Sorry, I'm not planning to port it to a new platform.

**Comment by ShikiSuen** [comment]
@audionuma

By the way, may I profit a little from my fork? The money will be used for my Developer Program membership fee and will only be charged through Mac App Store. Users don't have to pay to use this app but the consequence is that they have to manually compile the software by themselves.

**Comment by audionuma** [comment]
@ShikiSuen Hello. The license for libebur128 explicitly permits selling derived software, and (although I am not a lawyer) I think the GPL v3 license permits it also as long as the source code and the build instruction are provided.

Personally I have no problem with you charging for the builds on the app store as long as the above terms are respected.

**Pull request closed without merging**
